use std::env;
use std::fs;
use std::path::Path;
use std::process::Command;

fn main() {
    let project_root = env::var("CARGO_MANIFEST_DIR").unwrap();
    let c_dir = Path::new(&project_root).join("c");
    let c_bin_dir = c_dir.join("bin");
    let txt_dir = Path::new(&project_root).join("txt");
    let functions_json = txt_dir.join("functions.json");
    let build_dir = Path::new(&project_root).join("build");

    // --- Step 1: Build C code via make ---
    println!("cargo:warning=Building C collision modules...");

    fs::create_dir_all(&c_bin_dir).ok();

    let make_status = Command::new("make")
        .current_dir(&c_dir)
        .status()
        .expect("Failed to run make. Is mips-n64-gcc on PATH?");

    if !make_status.success() {
        panic!("make failed in c/");
    }

    // Watch C sources, Makefile, and ldpatcher
    for entry in fs::read_dir(c_dir.join("src")).unwrap() {
        let path = entry.unwrap().path();
        if path.extension().map_or(false, |ext| ext == "c" || ext == "h") {
            println!("cargo:rerun-if-changed={}", path.display());
        }
    }
    println!("cargo:rerun-if-changed={}", c_dir.join("Makefile").display());
    println!(
        "cargo:rerun-if-changed={}",
        c_dir.join("patch_ldscript.py").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        c_dir.join("sm64-api/sm64").display()
    );
    println!("cargo:rerun-if-changed={}", functions_json.display());

    // --- Step 2: Generate embedded_data.rs ---
    let functions_data = fs::read_to_string(&functions_json).unwrap();
    let functions: Vec<FunctionEntry> = serde_json::from_str(&functions_data).unwrap();

    let hardcoded_zero: std::collections::HashSet<&str> =
        ["min_3", "lower_cell_index", "upper_cell_index", "add_surface"]
            .into_iter()
            .collect();

    let mut patches: Vec<(String, u32, usize, Vec<u8>, bool)> = Vec::new();

    for func in &functions {
        let bin_path = c_bin_dir.join(format!("{}.bin", func.name));
        let has_bin = bin_path.exists();
        let is_hardcoded = hardcoded_zero.contains(func.name.as_str());

        if !has_bin && !is_hardcoded {
            continue;
        }

        let rom_addr: u32 =
            u32::from_str_radix(&func.rom_addr.replace("0x", ""), 16).unwrap();
        let length = func.length;

        let data = if has_bin {
            fs::read(&bin_path).unwrap()
        } else {
            vec![0u8; length]
        };

        patches.push((func.name.clone(), rom_addr, length, data, has_bin));
    }

    fs::create_dir_all(&build_dir).unwrap();
    let dest_path = build_dir.join("embedded_data.rs");

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — do not edit\n\n");

    code.push_str("pub struct PatchEntry {\n");
    code.push_str("    pub name: &'static str,\n");
    code.push_str("    pub rom_addr: u32,\n");
    code.push_str("    pub length: usize,\n");
    code.push_str("    pub data: &'static [u8],\n");
    code.push_str("    pub has_bin: bool,\n");
    code.push_str("}\n\n");

    for (i, (_name, _rom_addr, _length, data, _has_bin)) in patches.iter().enumerate() {
        let array_name = format!("PATCH_DATA_{}", i);
        code.push_str(&format!("static {}: &[u8] = &[\n", array_name));
        for chunk in data.chunks(16) {
            let hex: String = chunk
                .iter()
                .map(|b| format!("0x{:02X},", b))
                .collect::<Vec<_>>()
                .join("");
            let hex = hex.trim_end_matches(',');
            code.push_str(&format!("    {},\n", hex));
        }
        code.push_str("];\n\n");
    }

    code.push_str("pub const PATCHES: &[PatchEntry] = &[\n");
    for (i, (name, rom_addr, length, _, has_bin)) in patches.iter().enumerate() {
        code.push_str(&format!(
            "    PatchEntry {{ name: \"{}\", rom_addr: 0x{:08X}, length: {}, data: &PATCH_DATA_{}, has_bin: {} }},\n",
            name, rom_addr, length, i, has_bin
        ));
    }
    code.push_str("];\n");

    fs::write(&dest_path, code).unwrap();
    println!("cargo:warning=Generated {}", dest_path.display());
}

#[derive(serde::Deserialize)]
struct FunctionEntry {
    name: String,
    rom_addr: String,
    length: usize,
}
