use std::fs;
use std::path::Path;

fn main() {
    let project_root = env!("CARGO_MANIFEST_DIR");
    let c_bin_dir = Path::new(project_root).parent().unwrap().join("c").join("bin");
    let txt_dir = Path::new(project_root).parent().unwrap().join("txt");
    let functions_json = txt_dir.join("functions.json");

    // Watch for changes
    for entry in fs::read_dir(&c_bin_dir).unwrap() {
        let entry = entry.unwrap();
        println!("cargo:rerun-if-changed={}", entry.path().display());
    }
    println!("cargo:rerun-if-changed={}", functions_json.display());

    // Parse functions.json
    let functions_data = fs::read_to_string(&functions_json).unwrap();
    let functions: Vec<FunctionEntry> = serde_json::from_str(&functions_data).unwrap();

    // Hardcoded zero regions from patch_rom.py
    let hardcoded_zero: std::collections::HashSet<&str> =
        ["min_3", "lower_cell_index", "upper_cell_index", "add_surface"].into_iter().collect();

    // Collect patches: for each function, either load .bin or create zero-filled array
    let mut patches: Vec<(String, u32, usize, Vec<u8>, bool)> = Vec::new();

    for func in &functions {
        let has_bin = fs::exists(c_bin_dir.join(format!("{}.bin", func.name))).unwrap_or(false);
        let is_hardcoded = hardcoded_zero.contains(func.name.as_str());

        if !has_bin && !is_hardcoded {
            continue;
        }

        let rom_addr: u32 = u32::from_str_radix(&func.rom_addr.replace("0x", ""), 16).unwrap();
        let length = func.length;

        let data = if has_bin {
            fs::read(c_bin_dir.join(format!("{}.bin", func.name))).unwrap()
        } else {
            vec![0u8; length]
        };

        patches.push((func.name.clone(), rom_addr, length, data, has_bin));
    }

    // Generate Rust source file in build/ directory relative to CARGO_MANIFEST_DIR
    let manifest_dir = env!("CARGO_MANIFEST_DIR");
    let build_dir = Path::new(manifest_dir).join("build");
    std::fs::create_dir_all(&build_dir).unwrap();
    let dest_path = build_dir.join("embedded_data.rs");

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs — do not edit\n\n");

    // Struct definitions
    code.push_str("pub struct PatchEntry {\n");
    code.push_str("    pub name: &'static str,\n");
    code.push_str("    pub rom_addr: u32,\n");
    code.push_str("    pub length: usize,\n");
    code.push_str("    pub data: &'static [u8],\n");
    code.push_str("    pub has_bin: bool,\n");
    code.push_str("}\n\n");

    // Write binary data as static arrays
    for (i, (_name, _rom_addr, _length, data, _has_bin)) in patches.iter().enumerate() {
        let array_name = format!("PATCH_DATA_{}", i);
        code.push_str(&format!("static {}: &[u8] = &[\n", array_name));
        for chunk in data.chunks(16) {
            let hex: String = chunk
                .iter()
                .map(|b| format!("0x{:02X},", b))
                .collect::<Vec<_>>()
                .join("");
            // Remove trailing comma from the last byte, then add line comma
            let hex = hex.trim_end_matches(',');
            code.push_str(&format!("    {},\n", hex));
        }
        code.push_str("];\n\n");
    }

    // Patches array
    code.push_str("pub const PATCHES: &[PatchEntry] = &[\n");
    for (i, (name, rom_addr, length, _, has_bin)) in patches.iter().enumerate() {
        code.push_str(&format!(
            "    PatchEntry {{ name: \"{}\", rom_addr: 0x{:08X}, length: {}, data: &PATCH_DATA_{}, has_bin: {} }},\n",
            name, rom_addr, length, i, has_bin
        ));
    }
    code.push_str("];\n");

    fs::write(&dest_path, code).unwrap();
}

#[derive(serde::Deserialize)]
struct FunctionEntry {
    name: String,
    rom_addr: String,
    length: usize,
}
